In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
rng = np.random.default_rng(seed = 42)

In [5]:
rangee = np.arange(5)

In [15]:
rng.choice(rangee, 3 )

array([3, 3, 2])

In [12]:
rng.choice(rangee, 3,replace = False ) #

array([2, 3, 4])

In [13]:
rng.choice(rangee, 3,replace = False )

array([1, 4, 0])

In [14]:
rng.choice(rangee, 3 )

array([1, 0, 4])