In [2]:
import numpy as np

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
x = [1, 2, 3]
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])