# PCA question

In [43]:
import numpy as np
import matplotlib.pyplot as plt

## Know the data

In [44]:
# DATA CELL
# DO NOT EDIT THIS
X = np.array([
    [7, 5, -6, -11, 14.4, -2.8],
    [10.5, 7.5, -9, -16.5, 21.6, -4.2],
    [21, 15, -18, -33, 43.2, -8.4]
]).astype(np.float64)

In [46]:
d , n = X.shape
print(d) # no of feature
print(n) # no of datapoints

3
6


## Mean center the data

In [47]:
X_mean = X.mean()
X_mean

2.016666666666667

In [48]:
X

array([[  7. ,   5. ,  -6. , -11. ,  14.4,  -2.8],
       [ 10.5,   7.5,  -9. , -16.5,  21.6,  -4.2],
       [ 21. ,  15. , -18. , -33. ,  43.2,  -8.4]])

In [49]:
X = X - X_mean
X

array([[  4.98333333,   2.98333333,  -8.01666667, -13.01666667,
         12.38333333,  -4.81666667],
       [  8.48333333,   5.48333333, -11.01666667, -18.51666667,
         19.58333333,  -6.21666667],
       [ 18.98333333,  12.98333333, -20.01666667, -35.01666667,
         41.18333333, -10.41666667]])

In [50]:
cov_matrix = X @ X.T /n
cov_matrix

array([[ 73.99694444, 110.07111111, 218.29361111],
       [110.07111111, 164.73694444, 328.73444444],
       [218.29361111, 328.73444444, 660.05694444]])

In [51]:
eigval , eigvec = np.linalg.eigh(cov_matrix)
print(f"{eigval=}")
print(f"{eigvec=}")

eigval=array([-1.00930955e-14,  2.15685183e+00,  8.96633982e+02])
eigvec=array([[ 0.58834841, -0.756767  , -0.28486815],
       [-0.78446454, -0.44874446, -0.42806985],
       [ 0.19611614,  0.47532317, -0.85767496]])


In [55]:
var = np.flip(eigval)
print(f"{var=}")
PC = np.flip(eigvec , axis = 1)
print(f"{PC=}")

var=array([ 8.96633982e+02,  2.15685183e+00, -1.00930955e-14])
PC=array([[-0.28486815, -0.756767  ,  0.58834841],
       [-0.42806985, -0.44874446, -0.78446454],
       [-0.85767496,  0.47532317,  0.19611614]])


In [ ]:
round(np.abs(PC[:,0].sum()*7)) # round absolute value of 7a 
# where a is the 

11